const mongoose = require('mongoose');
const dotenv = require('dotenv');
const User = require('../models/User');
const Vehicle = require('../models/Vehicle');

// Load environment variables
dotenv.config({ path: './config.env' });

const connectDB = async () => {
    try {
        const conn = await mongoose.connect(process.env.MONGODB_URI, {
            useNewUrlParser: true,
            useUnifiedTopology: true,
        });
        console.log(`MongoDB Connected: ${conn.connection.host}`);
    } catch (error) {
        console.error(`Error: ${error.message}`);
        process.exit(1);
    }
};

const seedUsers = async () => {
    const users = [
        {
            username: 'admin',
            email: 'admin@auction.com',
            password: 'admin123',
            firstName: 'Admin',
            lastName: 'User',
            role: 'admin'
        },
        {
            username: 'john_doe',
            email: 'john@example.com',
            password: 'password123',
            firstName: 'John',
            lastName: 'Doe',
            role: 'user'
        },
        {
            username: 'jane_smith',
            email: 'jane@example.com',
            password: 'password123',
            firstName: 'Jane',
            lastName: 'Smith',
            role: 'user'
        },
        {
            username: 'bob_wilson',
            email: 'bob@example.com',
            password: 'password123',
            firstName: 'Bob',
            lastName: 'Wilson',
            role: 'user'
        },
        {
            username: 'alice_brown',
            email: 'alice@example.com',
            password: 'password123',
            firstName: 'Alice',
            lastName: 'Brown',
            role: 'user'
        }
    ];

    for (const userData of users) {
        const existingUser = await User.findOne({
            $or: [{ email: userData.email }, { username: userData.username }]
        });

        if (!existingUser) {
            await User.create(userData);
            console.log(`Created user: ${userData.username}`);
        } else {
            console.log(`User already exists: ${userData.username}`);
        }
    }
};

const seedVehicles = async () => {
    const vehicles = [
        {
            runNumber: 'A25',
            vin: '1HGBH41JXMN109186',
            year: 2021,
            make: 'Honda',
            model: 'Civic',
            trim: 'EX',
            mileage: 15000,
            mileageType: 'ACTUAL',
            color: 'Blue',
            seller: 'ABC Motors',
            description: 'Excellent condition, one owner, full service history',
            images: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=400&h=200&fit=crop&crop=center'],
            startingBid: 15000,
            bidIncrement: 500,
            reservePrice: 18000,
            condition: 'excellent',
            features: ['Bluetooth', 'Backup Camera', 'Lane Assist', 'Apple CarPlay'],
            engine: '1.5L Turbo I4',
            transmission: 'CVT',
            drivetrain: 'FWD',
            fuelType: 'Gasoline',
            fuelEconomy: { city: 30, highway: 38 },
            cylinders: 4,
            displacement: '1.5L',
            horsepower: 180,
            torque: 177,
            exteriorColor: 'Blue',
            interiorColor: 'Black',
            bodyStyle: 'Sedan',
            doors: 4,
            seats: 5
        },
        {
            runNumber: 'A26',
            vin: '2T1BURHE0JC123456',
            year: 2018,
            make: 'Toyota',
            model: 'Camry',
            trim: 'SE',
            mileage: 45000,
            mileageType: 'ACTUAL',
            color: 'Silver',
            seller: 'XYZ Auto',
            description: 'Well maintained, clean title, great fuel economy',
            images: ['https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=400&h=200&fit=crop&crop=center'],
            startingBid: 18000,
            bidIncrement: 1000,
            reservePrice: 22000,
            condition: 'good',
            features: ['Navigation', 'Leather Seats', 'Sunroof', 'Safety Sense'],
            engine: '2.5L I4',
            transmission: '8-Speed Automatic',
            drivetrain: 'FWD',
            fuelType: 'Gasoline',
            fuelEconomy: { city: 28, highway: 39 },
            cylinders: 4,
            displacement: '2.5L',
            horsepower: 203,
            torque: 184,
            exteriorColor: 'Silver',
            interiorColor: 'Black',
            bodyStyle: 'Sedan',
            doors: 4,
            seats: 5
        },
        {
            runNumber: 'A27',
            vin: '3VWDX7AJ5DM123456',
            year: 2013,
            make: 'Volkswagen',
            model: 'Jetta',
            trim: 'S',
            mileage: 75000,
            mileageType: 'ACTUAL',
            color: 'White',
            seller: 'DEF Cars',
            description: 'Reliable German engineering, good condition',
            images: ['https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400&h=200&fit=crop&crop=center'],
            startingBid: 8500,
            bidIncrement: 250,
            reservePrice: 12000,
            condition: 'good',
            features: ['Bluetooth', 'Cruise Control', 'Power Windows', 'ABS'],
            engine: '2.0L I4',
            transmission: '6-Speed Automatic',
            drivetrain: 'FWD',
            fuelType: 'Gasoline',
            fuelEconomy: { city: 24, highway: 34 },
            cylinders: 4,
            displacement: '2.0L',
            horsepower: 115,
            torque: 125,
            exteriorColor: 'White',
            interiorColor: 'Black',
            bodyStyle: 'Sedan',
            doors: 4,
            seats: 5
        },
        {
            runNumber: 'A28',
            vin: '4T1BF1FK5CU123456',
            year: 2012,
            make: 'Toyota',
            model: 'Corolla',
            trim: 'LE',
            mileage: 95000,
            mileageType: 'ACTUAL',
            color: 'Red',
            seller: 'GHI Motors',
            description: 'High mileage but well maintained, reliable daily driver',
            images: ['https://images.unsplash.com/photo-1582639510494-c80b5de9f148?w=400&h=200&fit=crop&crop=center'],
            startingBid: 6500,
            bidIncrement: 200,
            reservePrice: 9000,
            condition: 'fair',
            features: ['CD Player', 'Power Locks', 'Air Conditioning', 'Traction Control'],
            engine: '1.8L I4',
            transmission: '4-Speed Automatic',
            drivetrain: 'FWD',
            fuelType: 'Gasoline',
            fuelEconomy: { city: 26, highway: 34 },
            cylinders: 4,
            displacement: '1.8L',
            horsepower: 132,
            torque: 128,
            exteriorColor: 'Red',
            interiorColor: 'Gray',
            bodyStyle: 'Sedan',
            doors: 4,
            seats: 5
        },
        {
            runNumber: 'A29',
            vin: '5NPE34AF5FH123456',
            year: 2015,
            make: 'Hyundai',
            model: 'Sonata',
            trim: 'Sport',
            mileage: 60000,
            mileageType: 'ACTUAL',
            color: 'Black',
            seller: 'JKL Auto',
            description: 'Sporty sedan with good performance and features',
            images: ['https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400&h=200&fit=crop&crop=center'],
            startingBid: 12000,
            bidIncrement: 500,
            reservePrice: 16000,
            condition: 'good',
            features: ['Sport Package', 'Leather Seats', 'Navigation', 'Bluetooth'],
            engine: '2.0L Turbo I4',
            transmission: '6-Speed Automatic',
            drivetrain: 'FWD',
            fuelType: 'Gasoline',
            fuelEconomy: { city: 23, highway: 32 },
            cylinders: 4,
            displacement: '2.0L',
            horsepower: 245,
            torque: 260,
            exteriorColor: 'Black',
            interiorColor: 'Black',
            bodyStyle: 'Sedan',
            doors: 4,
            seats: 5
        },
        {
            runNumber: 'A30',
            vin: '6G1ZT51806L123456',
            year: 2006,
            make: 'Chevrolet',
            model: 'Impala',
            trim: 'LT',
            mileage: 120000,
            mileageType: 'ACTUAL',
            color: 'Gray',
            seller: 'MNO Cars',
            description: 'Classic American sedan, good for parts or restoration',
            images: ['https://images.unsplash.com/photo-1614200187524-dc4b892acf16?w=400&h=200&fit=crop&crop=center'],
            startingBid: 3500,
            bidIncrement: 100,
            reservePrice: 5000,
            condition: 'poor',
            features: ['V6 Engine', 'Power Windows', 'Air Conditioning', 'CD Player'],
            engine: '3.5L V6',
            transmission: '4-Speed Automatic',
            drivetrain: 'FWD',
            fuelType: 'Gasoline',
            fuelEconomy: { city: 19, highway: 28 },
            cylinders: 6,
            displacement: '3.5L',
            horsepower: 211,
            torque: 214,
            exteriorColor: 'Gray',
            interiorColor: 'Gray',
            bodyStyle: 'Sedan',
            doors: 4,
            seats: 6
        },
        {
            runNumber: 'A31',
            vin: '1FADP3F20FL123456',
            year: 2015,
            make: 'Ford',
            model: 'Fusion',
            trim: 'SE',
            mileage: 68000,
            mileageType: 'ACTUAL',
            color: 'White',
            seller: 'PQR Motors',
            description: 'Comfortable midsize sedan with great fuel efficiency',
            images: ['https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400&h=200&fit=crop&crop=center'],
            startingBid: 11000,
            bidIncrement: 500,
            reservePrice: 15000,
            condition: 'good',
            features: ['SYNC System', 'Backup Camera', 'Bluetooth', 'Cruise Control'],
            engine: '1.5L EcoBoost I4',
            transmission: '6-Speed Automatic',
            drivetrain: 'FWD',
            fuelType: 'Gasoline',
            fuelEconomy: { city: 23, highway: 36 },
            cylinders: 4,
            displacement: '1.5L',
            horsepower: 181,
            torque: 185,
            exteriorColor: 'White',
            interiorColor: 'Black',
            bodyStyle: 'Sedan',
            doors: 4,
            seats: 5
        },
        {
            runNumber: 'A32',
            vin: '2HNYD2H89CH123456',
            year: 2012,
            make: 'Honda',
            model: 'CR-V',
            trim: 'EX-L',
            mileage: 85000,
            mileageType: 'ACTUAL',
            color: 'Silver',
            seller: 'STU Auto',
            description: 'Reliable SUV with excellent safety ratings',
            images: ['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=400&h=200&fit=crop&crop=center'],
            startingBid: 14000,
            bidIncrement: 750,
            reservePrice: 18000,
            condition: 'good',
            features: ['AWD', 'Leather Seats', 'Navigation', 'Bluetooth'],
            engine: '2.4L I4',
            transmission: '5-Speed Automatic',
            drivetrain: 'AWD',
            fuelType: 'Gasoline',
            fuelEconomy: { city: 22, highway: 30 },
            cylinders: 4,
            displacement: '2.4L',
            horsepower: 185,
            torque: 163,
            exteriorColor: 'Silver',
            interiorColor: 'Black',
            bodyStyle: 'SUV',
            doors: 5,
            seats: 5
        },
        {
            runNumber: 'A33',
            vin: '3CZRU6H35MM123456',
            year: 2021,
            make: 'Honda',
            model: 'HR-V',
            trim: 'Sport',
            mileage: 22000,
            mileageType: 'ACTUAL',
            color: 'Blue',
            seller: 'VWX Cars',
            description: 'Compact SUV with modern technology and great fuel economy',
            images: ['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=400&h=200&fit=crop&crop=center'],
            startingBid: 22000,
            bidIncrement: 1000,
            reservePrice: 26000,
            condition: 'excellent',
            features: ['Apple CarPlay', 'Android Auto', 'LaneWatch', 'Honda Sensing'],
            engine: '1.8L I4',
            transmission: 'CVT',
            drivetrain: 'FWD',
            fuelType: 'Gasoline',
            fuelEconomy: { city: 28, highway: 34 },
            cylinders: 4,
            displacement: '1.8L',
            horsepower: 141,
            torque: 127,
            exteriorColor: 'Blue',
            interiorColor: 'Black',
            bodyStyle: 'SUV',
            doors: 5,
            seats: 5
        },
        {
            runNumber: 'A34',
            vin: '4T3ZF19C5YU123456',
            year: 2000,
            make: 'Toyota',
            model: 'Avalon',
            trim: 'XLS',
            mileage: 145000,
            mileageType: 'ACTUAL',
            color: 'Gold',
            seller: 'YZA Motors',
            description: 'Luxury sedan with smooth ride, high mileage but well maintained',
            images: ['https://images.unsplash.com/photo-1614200187524-dc4b892acf16?w=400&h=200&fit=crop&crop=center'],
            startingBid: 4500,
            bidIncrement: 200,
            reservePrice: 6500,
            condition: 'fair',
            features: ['Leather Seats', 'Sunroof', 'Premium Sound', 'V6 Engine'],
            engine: '3.0L V6',
            transmission: '4-Speed Automatic',
            drivetrain: 'FWD',
            fuelType: 'Gasoline',
            fuelEconomy: { city: 20, highway: 28 },
            cylinders: 6,
            displacement: '3.0L',
            horsepower: 210,
            torque: 220,
            exteriorColor: 'Gold',
            interiorColor: 'Tan',
            bodyStyle: 'Sedan',
            doors: 4,
            seats: 5
        },
        {
            runNumber: 'A35',
            vin: '5NMSH13E55H123456',
            year: 2005,
            make: 'Hyundai',
            model: 'Sonata',
            trim: 'GLS',
            mileage: 110000,
            mileageType: 'ACTUAL',
            color: 'Green',
            seller: 'BCD Auto',
            description: 'Reliable family sedan with good fuel economy',
            images: ['https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=400&h=200&fit=crop&crop=center'],
            startingBid: 3800,
            bidIncrement: 150,
            reservePrice: 5500,
            condition: 'fair',
            features: ['CD Player', 'Power Windows', 'Air Conditioning', 'ABS'],
            engine: '2.4L I4',
            transmission: '4-Speed Automatic',
            drivetrain: 'FWD',
            fuelType: 'Gasoline',
            fuelEconomy: { city: 23, highway: 32 },
            cylinders: 4,
            displacement: '2.4L',
            horsepower: 162,
            torque: 164,
            exteriorColor: 'Green',
            interiorColor: 'Gray',
            bodyStyle: 'Sedan',
            doors: 4,
            seats: 5
        },
        {
            runNumber: 'A36',
            vin: '6G1ZT51806L123457',
            year: 2019,
            make: 'Chevrolet',
            model: 'Malibu',
            trim: 'LT',
            mileage: 35000,
            mileageType: 'ACTUAL',
            color: 'Black',
            seller: 'EFG Motors',
            description: 'Modern sedan with advanced safety features',
            images: ['https://images.unsplash.com/photo-1582639510494-c80b5de9f148?w=400&h=200&fit=crop&crop=center'],
            startingBid: 16000,
            bidIncrement: 750,
            reservePrice: 20000,
            condition: 'excellent',
            features: ['Chevrolet Infotainment', 'OnStar', 'Backup Camera', 'Bluetooth'],
            engine: '1.5L Turbo I4',
            transmission: 'CVT',
            drivetrain: 'FWD',
            fuelType: 'Gasoline',
            fuelEconomy: { city: 29, highway: 36 },
            cylinders: 4,
            displacement: '1.5L',
            horsepower: 163,
            torque: 184,
            exteriorColor: 'Black',
            interiorColor: 'Black',
            bodyStyle: 'Sedan',
            doors: 4,
            seats: 5
        },
        {
            runNumber: 'A37',
            vin: '7FARW2H89CH123456',
            year: 2017,
            make: 'Nissan',
            model: 'Altima',
            trim: 'SR',
            mileage: 52000,
            mileageType: 'ACTUAL',
            color: 'Red',
            seller: 'HIJ Cars',
            description: 'Sporty sedan with good performance and reliability',
            images: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=400&h=200&fit=crop&crop=center'],
            startingBid: 13500,
            bidIncrement: 600,
            reservePrice: 17000,
            condition: 'good',
            features: ['NissanConnect', 'Sport Package', 'Bluetooth', 'Backup Camera'],
            engine: '2.5L I4',
            transmission: 'CVT',
            drivetrain: 'FWD',
            fuelType: 'Gasoline',
            fuelEconomy: { city: 27, highway: 39 },
            cylinders: 4,
            displacement: '2.5L',
            horsepower: 182,
            torque: 180,
            exteriorColor: 'Red',
            interiorColor: 'Black',
            bodyStyle: 'Sedan',
            doors: 4,
            seats: 5
        },
        {
            runNumber: 'A38',
            vin: '8XJDF4G23KL123456',
            year: 2014,
            make: 'BMW',
            model: '3 Series',
            trim: '328i',
            mileage: 72000,
            mileageType: 'ACTUAL',
            color: 'White',
            seller: 'KLM Motors',
            description: 'Luxury sedan with premium features and performance',
            images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400&h=200&fit=crop&crop=center'],
            startingBid: 18000,
            bidIncrement: 1000,
            reservePrice: 24000,
            condition: 'good',
            features: ['iDrive System', 'Leather Seats', 'Navigation', 'Premium Sound'],
            engine: '2.0L Turbo I4',
            transmission: '8-Speed Automatic',
            drivetrain: 'RWD',
            fuelType: 'Gasoline',
            fuelEconomy: { city: 23, highway: 35 },
            cylinders: 4,
            displacement: '2.0L',
            horsepower: 240,
            torque: 255,
            exteriorColor: 'White',
            interiorColor: 'Black',
            bodyStyle: 'Sedan',
            doors: 4,
            seats: 5
        },
        {
            runNumber: 'A39',
            vin: '9BWDE21J734123456',
            year: 2016,
            make: 'Volkswagen',
            model: 'Passat',
            trim: 'SE',
            mileage: 58000,
            mileageType: 'ACTUAL',
            color: 'Silver',
            seller: 'NOP Auto',
            description: 'European sedan with refined driving dynamics',
            images: ['https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=400&h=200&fit=crop&crop=center'],
            startingBid: 12500,
            bidIncrement: 500,
            reservePrice: 16000,
            condition: 'good',
            features: ['VW Car-Net', 'Bluetooth', 'Backup Camera', 'Cruise Control'],
            engine: '1.8L Turbo I4',
            transmission: '6-Speed Automatic',
            drivetrain: 'FWD',
            fuelType: 'Gasoline',
            fuelEconomy: { city: 25, highway: 38 },
            cylinders: 4,
            displacement: '1.8L',
            horsepower: 170,
            torque: 184,
            exteriorColor: 'Silver',
            interiorColor: 'Black',
            bodyStyle: 'Sedan',
            doors: 4,
            seats: 5
        },
        {
            runNumber: 'A40',
            vin: '1ZVBP8CF4E5123456',
            year: 2014,
            make: 'Ford',
            model: 'Mustang',
            trim: 'GT',
            mileage: 65000,
            mileageType: 'ACTUAL',
            color: 'Yellow',
            seller: 'QRS Cars',
            description: 'American muscle car with powerful V8 engine',
            images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400&h=200&fit=crop&crop=center'],
            startingBid: 22000,
            bidIncrement: 1000,
            reservePrice: 28000,
            condition: 'good',
            features: ['V8 Engine', 'Leather Seats', 'Premium Sound', 'Performance Package'],
            engine: '5.0L V8',
            transmission: '6-Speed Manual',
            drivetrain: 'RWD',
            fuelType: 'Gasoline',
            fuelEconomy: { city: 15, highway: 26 },
            cylinders: 8,
            displacement: '5.0L',
            horsepower: 420,
            torque: 390,
            exteriorColor: 'Yellow',
            interiorColor: 'Black',
            bodyStyle: 'Coupe',
            doors: 2,
            seats: 4
        }
    ];

    for (const vehicleData of vehicles) {
        const existingVehicle = await Vehicle.findOne({
            $or: [{ vin: vehicleData.vin }, { runNumber: vehicleData.runNumber }]
        });

        if (!existingVehicle) {
            await Vehicle.create(vehicleData);
            console.log(`Created vehicle: ${vehicleData.year} ${vehicleData.make} ${vehicleData.model}`);
        } else {
            console.log(`Vehicle already exists: ${vehicleData.runNumber}`);
        }
    }
};

const seedDatabase = async () => {
    try {
        await connectDB();

        console.log('Seeding users...');
        await seedUsers();

        console.log('Seeding vehicles...');
        await seedVehicles();

        console.log('Database seeded successfully!');
        process.exit(0);
    } catch (error) {
        console.error('Seeding error:', error);
        process.exit(1);
    }
};

// Run the seed function
seedDatabase(); 